### PR TITLE
docs: change bash to sh in markdown syntax

### PR DESCRIPTION
**Pull request by milrope**
change `bash` to `sh`as code blocks language identifier for shell commands as they don't have anything specific to `bash`

### CODE REVIEW

**Comment by compnerd** [comment]
Thanks for your contribution!

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by compnerd** [comment]
@swift-ci please smoke test Linux platform

**Comment by CodaFi** [comment]
@swift-ci clean smoke test Linux platform

**Comment by CodaFi** [comment]
⛵

**Pull request merged**
